### ISSUE TITLE
Support bookmarks in links

### ISSUE THREAD

**Issue by AxelTheGerman** [lihanli/cone#1]
Hi,

I thought it would be pretty useful if one could add a bookmark part to the URL, similar to how the query string works.

```javascript
// current
cone.userPath({id: 12, foo: 'bar baz'});
"/users/12?foo=bar%20baz"

// suggested
cone.userPath({id: 12, bookmark: 'preferences', foo: 'bar baz'});
"/users/12#preferences?foo=bar%20baz"
```
maybe we could come up with a better way than turning `bookmarks` magically into `#preferences` instead of treating it as all the other query params.

especially useful when the URL points to an index page with a longer list of items (all with an ID attribute) this would allow to scroll to a specific item in the list.

Let me know what you thing and if you'd like any help/PR on that.

**Comment by lihanli** [comment]
good idea, i added it under the anchor option which works the same way as it does in rails
```ruby
user_path(id: 1, anchor: 'foo') # => "/users/1#foo"
```
